
import os
from typing import Dict, Tuple

CAPITAL = 100000
MAX_POSITION_SIZE = 0.10
TRADING_DAYS = 252
TRANSACTION_COST_BPS = 5

Z_ENTRY = 2.0
Z_EXIT = 0.5
Z_MAX_POSITION = 3.5

COINT_PVALUE_THRESHOLD = 0.05
MIN_HALFLIFE = 5
MAX_HALFLIFE = 252
MIN_CORRELATION = 0.7
LOOKBACK_COINT = 252

ROLLING_WINDOW_ZSCORE = 60
ROLLING_WINDOW_REGRESSION = 252
ROLLING_WINDOW_VOL = 30
MIN_OBSERVATIONS = 20

REGIME_DETECTION_METHOD = "hmm"
N_REGIMES = 2
VOLATILITY_CLUSTERING_WINDOW = 20
VOL_ADJUSTMENT_SCALE = 1.0

MAX_DRAWDOWN_LIMIT = -0.20
LEVERAGE_LIMIT = 2.0
MIN_SHARPE_THRESHOLD = 0.5
POSITION_LIMIT = 2

TRAIN_WINDOW = 252
TEST_WINDOW = 63
REBALANCE_FREQUENCY = "daily"
SLIPPAGE_BPS = 2

RANDOM_STATE = 42
CV_FOLDS = 5
OPTIMIZATION_METHOD = "grid"
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(PROJECT_ROOT, "data", "raw")
RESULTS_PATH = os.path.join(PROJECT_ROOT, "results")
LOGS_PATH = os.path.join(PROJECT_ROOT, "logs")

os.makedirs(RESULTS_PATH, exist_ok=True)
os.makedirs(LOGS_PATH, exist_ok=True)

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

TICKERS_UNIVERSE = ["AAPL", "MSFT", "GOOGL"]
MIN_PAIRS_TO_TRADE = 1

ASSET_GROUPS: Dict[str, list] = {
    "tech": ["AAPL", "MSFT", "GOOGL"],
    "index": ["SP500", "NASDAQ"],
}

